### ISSUE TITLE
Improve Wave Warp Effect

### ISSUE THREAD

**Issue by freewarecamp** [axiomgraph/enve-plugins#5]
The Wave warp effect is really useful. But it need some new parameter like a direction for the wave warp effect and a time/evoulution/shift to animate the wave. Thank You

**Comment by axiomgraph** [comment]
I ported new code from olive video editor project in which frequency, intensity,evolution and vertical options are available.

**Comment by freewarecamp** [comment]
Just What we needed, Thanks a Ton Bro :)
