### ISSUE TITLE
Tunnel Effect Error 

### ISSUE THREAD

**Issue by freewarecamp** [axiomgraph/enve-plugins#6]
Hello, Im getting this error
![image](https://user-images.githubusercontent.com/86367188/206682861-4fa967a2-affc-45f6-a937-86f2cd46f879.png)

**Comment by axiomgraph** [comment]
my mistake I forget to remove some lines. can you check again

**Comment by freewarecamp** [comment]
Thank You, It's Working :) It's A Dope Effect Honestly!
