### ISSUE TITLE
Error Using Files from version 1

### ISSUE THREAD

**Issue by freewarecamp** [axiomgraph/enve-plugins#7]
I know this is really frustrating but they are back for no reason. I switched to W11 and re-installed enve then tried to use these plugins again and this is happening. All of them are showing error. But when i use files from version 2 there is no error. And I'm currently using a laptop with intel i5 @1.6Ghz with intel uhd graphocs (its an old laptop). The recording was big so I gave a drive link. Please Check it and Give a Solution

https://drive.google.com/file/d/1gRVDh7Oygp8YPvgqzF9T4lQk01IjTcw7/view?usp=drive_link

**Comment by axiomgraph** [comment]
bro the difference between two versions are simple. the version one uses "texture2d" function and the version 2 uses "texture" function
other than that the code in both versions are similar the results that get from both versions is also same. so don't worry the code is fine.
![function](https://github.com/axiomgraph/enve-plugins/assets/68183694/63e169a4-8c71-402d-af5e-d80fc0ee4151)

**Comment by freewarecamp** [comment]
can you maake all the effects available on version 2?

**Comment by axiomgraph** [comment]
will add more plugins to version 2 from version 1 folder
