### ISSUE TITLE
Make an official repo for Friction?

### ISSUE THREAD

**Issue by rodlie** [axiomgraph/enve-plugins#8]
Would you mind if I fork or create an official `friction-plugins` repo at https://github.com/friction2d with the content (and history) of this repo? With the option to bundle them (all or some) with the application.

**Comment by axiomgraph** [comment]
I have no problem with that. and you should add boolean input support and rewrite some codes.

**Comment by rodlie** [comment]
Great :+1: 

boolean (and string) parameter support is on the roadmap.
